---
- name: "Adding UFW rules"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/ufw-configure-rule.yml"
  vars:
    rules:
      - {rule: "allow", name: "Bind9", comment: "Allow DNS for All"}
